use crate::utils::logs::get_latest_log_symlink_path;
use super::CommandOption;

async fn callback() {
    println!("Showing the logs!");
}

pub fn get_option() -> CommandOption {
    let log_path = get_latest_log_symlink_path();
    let log_path_string = log_path.to_str().unwrap();

    CommandOption {
        string_identifiers: vec![String::from("logs")],
        callback: Box::new(|| Box::pin(callback())),
        description: format!("Shows latest logs generated by the program. Equivalent to running `$ cat {}`.", log_path_string),
    }
}
