use super::CommandOption;
use crate::init_command_option;
use crate::utils::logs::get_latest_log_symlink_path;
use std::fs;

fn get_log_path_string() -> String {
    let log_path = get_latest_log_symlink_path();
    log_path.to_str().unwrap().to_string()
}

async fn callback() {
    let log_path_string = get_log_path_string();
    let logs = fs::read_to_string(log_path_string.clone())
        .expect("Failed to read the latest log! Is the directory broken?");
    println!("{}", logs);
}

init_command_option!(
    vec!["logs"],
    format!(
        "Shows latest logs generated by the program. Equivalent to running `$ cat {}`.",
        get_log_path_string()
    ),
    callback
);
